#include "unity.h"
#include "mock_stdio.h"  // Auto-generated by Ceedling/CMock
#include "../src/my_functions/show_greetings.h" // contains show_greetings()

void test_show_greetings_should_print_correctly(void) {
    char name[] = "Ken";
    int age = 21;

    printf_Expect("おはようございます皆さん\n");
    printf_Expect("I'm %s, %d years old.", name, age);

    show_greetings(name, age);
}