# Just an arbitrary name
name: Unit Tests with Ceedling

# Sets when it will be triggered
on:
    push:
        branches: main
    pull_request:
        branches: main

# Number of jobs where it will run in order
# Step 1: checkout@v4: Gets the code from remote repository
# Step 2: setup-msys2@v2: Tells the runner (remote windows from Github) to setup MSYS2
# Step 3: Tells to use MSYS2 shell (or terminal) and compile the code
# Step 4: Run the program with the compiled code
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Set up Ruby
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: '3.3'

        - name: Install Ceedling
          run: gem install ceedling

        - name: Run Unit Tests
          run: ceedling test:all gcov:all
        
        - name: Upload JUnit Test Report
          uses: actions/upload-artifact@v4
          with:
            name: junit-report
            path: build/artifacts/test/results/*.xml
        
        - name: Upload HTML coverage report
          uses: actions/upload-artifact@v4
          with:
            name: code-coverage
            path: build/artifacts/gcov/**
